### ISSUE TITLE
There is no source code in the Pre-release versions

### ISSUE THREAD

**Issue by ajbastien** [SR-G/bambu-lab-observer#4] opened 2023-10-23 00:48 UTC
Source code in pre release versions in just 2 images?

**Comment by enly1** [comment] 2023-10-23 07:47
He didn't upload source yet as it wasn't ready for prime time, but said he was planning to, which was why I raised ticket 3...

**Comment by SR-G** [comment] 2023-10-23 08:01
Correct. Hence closing this ticket, duplicate of #3

**Closed as completed by SR-G** 2023-10-23 08:01 UTC
Labels: duplicate
